transformers/socket.io/server.js
Fixes #330.
Signed-off-by: Joe Grund <grundjoseph@gmail.com>
=> [fix] Set client-store-expire option to 0 for socket.io

README.md, index.js, test/primus.test.js
=> Add ability to reconnect the clients when calling `primus.destroy`

README.md
=> added link to primus-android

index.js
This should correctly expose the constructor in the browser.
=> Correctly expose the Primus constructor

index.js
This should solve the [issue](https://github.com/primus/primus/pull/349#issuecomment-77326363) reported by @STRML.
=> Use a closure to preserve the plugins functionality

package.json, primus.js
In the release notes we wrote that our client is using the `url-parse` module, but it is actually still using the DOM based parse solution.
=> Use the `url-parse` module

index.js, package.json
This should make `istanbul` work.
=> Refactor the way we build the client for node

index.js, package.json
=> Revert "Refactor the way we build the client for node"

primus.js
This should solve #399 
One remaining question/issue is:
Currently the Primus#offline method calls Primus.end(), without checking if there is or not a pending reconnection. Since Primus#end() terminates any pending attempt to reconnect, is it the desired behavior?
We saw events in this order:
- Websocket error
- ```reconnect scheduled``` (attempt number 1)
- ```offline```
- ```end``` (caused by offline as explained above)
- ```online```
So in the end we lost the connection and did not reconnect automatically.
=> [fix] Remove offline & online handlers upon "destroy"

spark.js, test/transformer.base.js
=> Show loss of data during connection middlewares

primus.d.ts
This might not be 100% complete yet, but it does cover everything in the README doc and appears to be working properly in my project that uses Primus. I'll submit updates if I come across anything missing/wrong.
=> Added a TypeScript TSD for compatibility

primus.d.ts
Updated the TypeDefinition file to not throw implicit any errors, and also resolved duplicate namespacing issue.
=> Updating the type definition file.

package.json, test/lws.integration.js, transformers.json, transformers/lws/index.js, transformers/lws/server.js
This is the same as https://github.com/primus/primus/pull/439 but now things are published so tests should probably pass.
=> Add initial transformer for node-lws

README.md, transformers/uws/server.js
µWS has initial SSL support from v0.2.7
=> Update transformer inconsistencies

package.json, transformers/uws/server.js
This fixes some hard to trigger transfer bugs
=> [uws] Update transformer to v0.3.0 interface

transformers/uws/server.js
I broke the onDisconnection interface in v0.3.2. It now also passes code and message from the close frame.
=> [uws] v0.3.2 updates

README.md, index.js, test/transformer.base.js, transformers/engine.io/server.js, transformers/faye/server.js, transformers/sockjs/server.js, transformers/uws/server.js, transformers/websockets/server.js
This adds an option called `maxLength` to limit the maximum size of an incoming message. The option default value is 10 MiB.
Transformers have also been updated to use ES2015 syntax/features.
=> Introduce the `maxLength` option

spark.js
I think it's better to let the GC do its job here.
=> Do not forcibly remove the spark properties

transformers/uws/server.js
v0.12.0+ requires a set empty callback
=> Set "no operation" callback in uws transformer

README.md
Add primus-rooms-redis-adapter to the list of community plugins
=> [doc] add primus-rooms-redis-adapter

package.json
=> chore(package): update engine.io to version 2.0.1

package.json
=> chore(package): update engine.io-client to version 2.0.1

test/primus.test.js
Just a minor nitpick, this kills some of the console logging in the test suite.
=> [test] Squelch some console logging

primus.d.ts
Like discussed in #536 here is a typescript definition upgrade.
I just started with primus, so there could be some more changes needed.
=> updated primus.d.ts

index.js, spark.js, test/spark.test.js
=> [minor] Move heartbeat into Spark so it can be overridden

package.json
Closes #508
https://greenkeeper.io/
=> chore(package): update engine.io to version 3.0.0

package.json
Closes #509
https://greenkeeper.io/
=> chore(package): update engine.io-client to version 3.0.0

README.md
@lpinca Some changes re issue #571 
The second commit may be overkill after the first commit since there's no longer a mention of the client side library.
=> Update server side client connection docs

package.json
=> chore(package): update engine.io to version 3.1.0

package.json
Update engine.io-client to version 3.1.0
=> chore(package): update engine.io-client to version 3.1.0

package.json
=> chore(package): update chai to version 4.0.0

README.md, primus.d.ts, spark.js, test/primus.test.js, test/spark.test.js
Signed-off-by: Ryan Sivek <nanowizardry@gmail.com>
=> [feature] Add custom spark id generator option. Closes #551

package.json
=> chore(package): update engine.io-client to version 3.2.0

package.json
=> chore(package): update engine.io to version 3.2.0

README.md, package.json, spark.js
Use nanoid as default id generator.
Fixes #639
=> [minor] Replace yeast with nanoid

transformers/uws/server.js
=> [minor] Enable send compression with uws

transformers/sockjs/library.js
Update the SockJS client-side library to version 1.4.0
=> Rebuild the SockJS client -- version 1.4.0

transformers/engine.io/library.js
Update the Engine.IO client-side library to version 3.4.0
=> Rebuild the Engine.IO client -- version 3.4.0
