primus/primus

- primus.js
- transformers/browserchannel/client.js
- transformers/engine.io/client.js
- transformers/faye/client.js
- transformers/socket.io/client.js
- transformers/sockjs/client.js
- transformers/websockets/client.js
Not really happy with this, but it was the cleanest solution I could come up with.
> Defer all `incoming::` prefixed events except `incoming::pong`

- primus.js
For some reason in Firefox 31.4.0
window.Event.prototype.hasOwnProperty === undefined.
This causes an error in primus.on('incoming::error', ...)
and hence missing 'error' event.
> Fix undefined Event.prototype.hasOwnProperty issue.

- index.js
- test/primus.test.js
Renaming all `Primus` identifiers is no longer required.
This also fixes an issue in the closure introduced [here](https://github.com/primus/primus/pull/356). If I'm not wrong the `Primus` identifiers were not renamed [here](https://github.com/primus/primus/blob/76c4e8d292b70c8a06871a002375f17af823d0a4/index.js#L606), so it was probably broken when using a custom class name.
> Refactor the way we handle custom export names

- README.md
- spark.js
- test/spark.test.js
This fires every time the internal timeout timer is reset.
Due to #323 and anticipated further support for protocol-level ping/pong, this
can be useful as a catch-all for both types of heartbeats: 'primus::ping' and
the 'ping' control frame.
This can be useful for services that might want to know if a connection is
alive, whether the activity is a `ping` control frame or a message.
I found this useful in an application where I wanted to allow users to opt in
to heartbeating. Since it is not possible to set a heartbeat timeout per-spark,
one can simply wait for this event and cancel the timeout (`conn.timeout`).
Alternatively, for my use case, the `primus.timeout` property could be copied
to each spark as `spark.timeoutInterval` so it could be overridden by the
application, but I thought …
> Add a 'heartbeat' event.

- primus.js
- spark.js
There are 2 main reasons for this change:
1. Consistency with the `Spark` implementation.
2. Our broserified client overrides `JSON.stringify` when required in node.
> Don't override JSON.stringify

- spark.js
- test/spark.test.js
- transformers/websockets/server.js
We first check if a timestamp has been sent with the event.
If we don't have a timestamp, we assume that the event has been fired by a WebSocket ping and only reset the spark heartbeat.
> Tweak our `incoming::ping` listener to handle WebSocket pings

- primus.js
- transformers/browserchannel/client.js
- transformers/engine.io/client.js
- transformers/faye/client.js
- transformers/socket.io/client.js
- transformers/sockjs/client.js
- transformers/websockets/client.js
This patch slightly simplifies the `primus.uri` method by removing no longer needed code thanks to `url-parse`.
This also slightly changes the values of the `protocol` and `pathname` properties to make them a little more consistent with the `URLUtils` interface.
> Simplify `primus.uri` by taking advantage of `url-parse`

- index.js
- spark.js
- test/primus.test.js
By default the client sends the ping messages even when the heartbeat timeout is disabled.
To stop the client from sending these messages it is necessary to manually set the `ping` option to `false`.
With this patch the default value of the `ping` option is automatically set to `false` when the heartbeats are disabled.
> Set the `ping` option to `false` when the heartbeats are disabled

- package.json
- primus.js
**Pros**
- A shorter id
**Cons**
- A slightly bigger client-side library
> Use `yeast` to generate the cache-busting id

- README.md
The example section was originally written for the `events` example but it hasn't been updated since then. As result it doesn't cover all the other examples that have been added later.
I think that it makes sense to remove it given that:
- Each example has its own documentation.
- The `events` example that lives on nodejitsu will die soon unless it will be moved somewhere else.
> Remove the example section

- index.js
- test/plugin.test.js
```js
'use strict';
const Primus = require('primus');
const http = require('http');
let primus = new Primus(http.createServer());
primus.use('bogus', {
server : function srv(primus) {
primus.Spark.prototype.initialise = function init() {};
}
});
console.log(primus.Spark.prototype.__initialise);
// => [ [Function: initialise], [Function: init] ]
primus = new Primus(http.createServer());
console.log(primus.Spark.prototype.__initialise);
// => [ [Function: initialise], [Function: init] ]
```
The second instance does not use any plugins so the `__initialise` array
should not include the `init` function.
Add an `__initialise` property in the `Sparky` prototype which is a copy
of the original `__initialise` array from the `Spark` prototype.
> Prevent the Spark prototype from being mutated

- primus.js
- transformers/browserchannel/client.js
- transformers/engine.io/client.js
- transformers/faye/client.js
- transformers/socket.io/client.js
- transformers/sockjs/client.js
- transformers/websockets/client.js
When using `react-native` with `primus` generated lib will throw error
```
Unable to resolve module stream ....
```
after some debugging I have figured out that `react-native` packager assume that every method with name `require` is normal require method.
So replacing the function name with something else instead of `Primus.require` will fix that problem.
> rename Primus.require => Primus.requires

- primus.js
- transformers/engine.io/client.js
- transformers/faye/client.js
- transformers/socket.io/client.js
- transformers/sockjs/client.js
- transformers/websockets/client.js
This is a breaking and maybe unwanted change.
It fixes some open issues (#320, #263, #264) and possible race conditions.
It removes a [workaround](https://gist.github.com/mloughran/2052006) used to prevent iOS 5 from crashing under certain circumstances.
In short it's a f**k you to the users of iOS 5, but I would give a stable and bug free library to the majority of the users rather than a buggy one to everyone.
> Stop deferring the events on the client

- package.json
- transformers/engine.io/library.js
- transformers/engine.io/patches/activex.patch
- transformers/engine.io/patches/defer.patch
- transformers/engine.io/patches/utf8.patch
- transformers/socket.io/library.js
This completes #404 by removing the workaround for the iOS 5 WebSocket bug from the Socket.IO and Engine.IO client-side libraries.
> iOS 5 deprecation

- README.md
- package.json
- test/uws.integration.js
- transformers.json
- transformers/lws/server.js
- transformers/uws/index.js
- transformers/uws/server.js
This adds a new transfomer called `uws` which is the successor of `lws`.
> Add uws transformer

- index.js
if this is the case, a module loader is responsible, so we
don't care about exposing a global anyway
> Client: Fix #444: Don't error if there is no `this`

- index.js
- package.json
This patch brings the following changes:
- Use the `vm` module directly instead of depending on `load`.
- Remove the `load` dependency.
- Create a context for the Node.js client where only the required globals are added.
It should fix https://github.com/3rd-Eden/load/issues/4.
I'm actually not sure if it's better to do this in `load` and keep the dependency.
> Remove load dependency

- README.md
- index.js
- primus.js
- transformers/browserchannel/server.js
- transformers/engine.io/server.js
- transformers/faye/server.js
- transformers/socket.io/server.js
- transformers/sockjs/server.js
- transformers/uws/server.js
- transformers/websockets/server.js
This allows to use any configuration option supported by the underlying real-time framework.
There are use cases where this is useful. An example is when you want to limit the max frame size in `ws` or `faye-websocket-node`.
If we don't want this, because it defeats the effortless switching goal, I think that we should at least "wrap" the most important options (`maxPayload`/`maxLength` is one of these imho) like we did with `compression`.
> Add ability to use transformer specific configuration options

- README.md
- examples/middleware/index.js
- index.js
- migration.md
- test/middleware.test.js
- test/plugin.test.js
- test/primus.test.js
- test/transformer.base.js
This renames `Primus#use` to `Primus#plugin` and `Primus#before` to `Primus#use`.
It is nice to have as these names are better imho but it literally destroys the existing plugin ecosystem.
All plugins need to be updated if this gets merged and they will no longer be compatible with older versions of Primus.
It adds little value to Primus, so we can also keep the existing names and live with it.
Closes #287.
> Rename some public methods

- package.json
- parsers.json
- parsers/msgpack.js
- test/primus.parsers.test.js
This adds an experimental MessagePack parser.
It uses [`msgpack-lite`](https://github.com/kawanet/msgpack-lite) which is quite fast according to the benchmarks.
It could be used as an alternative to `binary-pack` which is incredibly slow when encoding.
> Add msgpack parser

- README.md
The last version of express 2.x was April 2012. It's highly unlikely anybody is using express 2.x four and a half years later. I've removed all reference to the express version to avoid confusion.
> Confusing express documentation change

- package.json
- test/transformer.base.js
- transformers/uws/server.js
This updates the uws transformer to make it work with `uws@0.10.x`.
The `maxPayload` option seems to be ignored by the current version of `uws` so tests fail.
> Fix compatibility with uws 0.10.x

- transformers/uws/server.js
Fixes #530 
Error handler and checking of readable/writable state is very similar to how this is [done in ws](https://github.com/websockets/ws/blob/95d8553ca657ce926934cd5d8b5eb3c7841f4422/lib/WebSocketServer.js#L150).
> [fix] Catch closed upgrade requests in `uws`

- transformers/uws/server.js
See also 76612fb which was applied for 'ws'.
> [uws] Support resetting heartbeat via protocol-level ping.

- README.md
- index.js
- primus.js
- spark.js
- test/primus.test.js
- test/spark.test.js
- test/transformer.base.js
- transformers/uws/server.js
- transformers/websockets/server.js
This reverses the direction of ping/pong messages. Ping messages are now sent from server to client to work around issues generated by throttled timers on modern browsers.
> Reverse the direction of ping/pong messages

- index.js
- test/transformer.base.js
#579 
Test uses `process._getActiveHandles()` to check `setInterval()` wasn't called.
Alternative would be to mock `setInterval`.
> Issue 579 Don't start heartbeat in createSocket

- primus.d.ts
Two fixes on typescript definitions :
- `parser` can be a string or an object with the `encoder` and `decoder` functions
- Allow other properties like `middleware` or `redis`, etc. (for plugin like metroplex)
> Fixes on typescript def

- primus.js
- test/plugin.test.js
This patch allows the cache busting parameter to be modified in a listener of the `outgoing::url` event.
Fixes #585.
> Add ability to modify the cache busting parameter

- README.md
Removed the utf8 magic on chaos and destruction, as it makes the lines surrounding it unreadable, and made myself and coworker wonder what was going on. Not sure how people consider the following readable:
As a rule of thumb assume that every event that is prefixed with `incoming::` or
`outgoing::` is reserved for internal use only and that emitting such events your
self will most likely result in c̮̫̞͚͉̮̙͕̳̲͉̤̗̹̮̦̪̖̱h̛͍͙̖̟͕̹͕̙̦̣̲̠̪̯̳͖̝̩a̴̝̦͇̥̠̟͚̳̤̹̗̻̭͍͖͕͓̻o̥̹̮̙͔̗͍͚͓̗̦̹͈͙͕̘̮͖̝ș̗̲̤̗̮͈̙͈̹̼̣̹̖̱̤̼̺̤ ̻͙̗̥̠̱͇̱̝̟̺͍̺̼͆̅̓̓̇a̜̖͈͇͎͙̲̙̗͇̫̘̖̹͖͓͔̺̱n̹͓̮͇̯̜̤̗͍̯̰̫̫̖̰ͬ͌ͬͫd͚̪͚̭͚̥̰̤̟͎̝̲̯̭̹̭̙̼̤ ͖̞̙̹͈͚̥̦͚͉͖̼̬͓͚̳͉͙͎d̴͚̱̮̗͍̩̻̰̣̫͉͈̞̲͉̫̞͔ẻͩͦ̃͌̿̐ͪͩ̌̇͂̆̑͐ͣ ҉̲͉͔͎̤̼̘͇̮̥̻̜̹̥͚̲̻̖s̶̗̻̫̼̠̳̗̺̤̗̳͈̪̮̗̝͇͈t̙͇͕̺̱̼̤̗̰̬̣͌ͬͧ͊́ͧͩ͌r͌̐̓̃ͥ̄ͤ͑̈ͬ͆ͬ͂̇̿̅ ҉̙̼̳̭̙͍̻̱̠͈̮̺̣̝̱̙̺͉ư̳͎̻͔̯̪̝͕͚̣̜̼̞͇̠̘̠̪c̨̫͙͙̬̰̰̫̐͋͊͑̌̾̉͆t͚̗͕̝̤̗͕̲̮̝̼̺͙͚̟͓̣̥͍ĭ͙̘̩̖͇͎̆̍̿̾ …
> README: make chaos and destruction readable

- middleware/authorization.js
#691 Calling destroy on the socket can mean the headers and message don't get away before the socket is destroyed.
Node doc for socket.destroy says:
Ensures that no more I/O activity happens on this socket.
Node doc for socket.end says:
Half-closes the socket. i.e., it sends a FIN packet.
> End upgrade connection rather than destroy #691

- spark.js
- transformers/browserchannel/server.js
- transformers/engine.io/server.js
- transformers/faye/server.js
- transformers/sockjs/server.js
- transformers/uws/server.js
- transformers/websockets/server.js
Over the past two days I've been trying to improve performance of my stack as much as possible, going as far as writing my own much simpler rooms extension and entirely stepping trough function calls. Having `primus.encoder.call` being called only once instead of per client whenever you emit to multiple clients at once in itself already gave me a massive peformance boost, and is implementable without modifying any core code, however there was a second step involved which I took and that is using uWs' `prepareMessage` / `sendPrepared` calls. This gave me yet another significant boost in troughput.
My plugin should be rather versatile, tho surely not fully compatible with all setups, however I feel like it should be a great addition to release. It would work without the modifications of …
> Expose transformers server and sparks underlying socket

- README.md
- index.js
- test/transformer.base.js
Just finally got around to change my proprietary rooms plugin implementation to one I could actually release and realized I failed to add the new socket variable introduced w/ #703 here, thus it always ending up "undefined". Oops, should've tested in advance, sorry!
> Add socket parameter in Spark constructor wrapper

- transformers/sockjs/server.js
Apparently there is an unidentified bug in SockJS whereby the connection object received in the 'connection' event handler is sometimes null. This has started to happen to us when we upgraded to Node v14 (from v10) and it has happened in production a few times already causing the entire server to collapse.
Please see https://github.com/sockjs/sockjs-node/issues/121 and also https://github.com/webpack/webpack-dev-server/commit/79649971c299f648fdd0ba3d4513a8cf7fc881d2 where webpack-dev-server implements a similar fix.
> [fix] Prevent "Cannot read property 'headers' of null"
